name: CI/CD with DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-web:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-web:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.0'

    - name: Set up Kind cluster
      uses: helm/kind-action@v1.7.0
      with:
        cluster_name: flask-k8s

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/flask-deployment flask-container=${{ secrets.altjin09 }}/flask-web:latest
        kubectl rollout status deployment/flask-deployment

